/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "keypad.h"
#include "lcd.h"
#include "EXTI.h"
#include "usart.h"
#include "spi.h"


#define MCU_Act_As_Slave
//#define MCU_Act_As_Mater

void clock_init()
{
	//Bit 2 IOPAEN: I/O port A clock enable
		RCC_GPIOA_CLK_EN();
	//Bit 3 IOPBEN: I/O port B clock enable
		RCC_GPIOB_CLK_EN();
		RCC_AFIO_CLK_EN();
}



void wait(int x)
{
	unsigned int i ,j;
	for(i=0;i<x;i++)
		for(j=0;j<255;j++);
}

uint16_t ch;

void SPI1_IRQ_CallBack(struct S_IRQ_SRC irq_src)
{

	#ifdef MCU_Act_As_Slave
	if(irq_src.RXNE)
	{
		ch = 0x0f;
		MCAL_SPI_TX_RX(SPI1, &ch, Pollingdisable);
		MCAL_UART_SendData(USART1, &ch, enable);
	}

	#endif

}







void UART_IRQ_Callback(void)
{

#ifdef MCU_Act_As_Mater
	MCAL_UART_RecieveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);
	// SPI
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 0);
	MCAL_SPI_TX_RX(SPI1, &ch, Pollingenable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);

#endif
}

int main(void)
{
	clock_init();
	UART_Config uartCFG;
	uartCFG.IRQ_CallBack = Default_IRQ_Cfg;
	uartCFG.BaudRate = USART_BaudRate_115200;
	uartCFG.HWFlowCTRL = UART_HWFlowCTRL_NONE;
	uartCFG.IRQ_Enable = USART_IRQ_Enable;
	uartCFG.IRQ_CallBack.P_IRQ_CallBack_RXNE = UART_IRQ_Callback;
	uartCFG.Parity = UART_Parity_NONE;
	uartCFG.Payload_Length = UART_Payload_Length_8B;
	uartCFG.StopBits = UART_StopBits__1;
	uartCFG.USART_Mode = UART_Mode_TX_RX;

	MCAL_UART_Init(USART1, &uartCFG);
	MCAL_UART_GPIO_Set_Pins(USART1);

	SPI_Config SPI1CFG;

	SPI1CFG.CLKPhase = SPI_Clock_Phase_2EDGE_first_data_capture_edge;
	SPI1CFG.CLKPolarity = SPI_CLKPolarity_HIGH_when_idle;
	SPI1CFG.Data_Size = SPI_DataSize_8BIT;
	SPI1CFG.Frame_Format = SPI_FRAME_FORMAT_MSB_transmmitted_first;
	// default pclk = 8Mhz
	SPI1CFG.SPI_BAUDRATEPRESCALER = SPI_BAUDRATEPRESCALER_8;
	SPI1CFG.Communicaion_Mode = SPI_DIRECTION_2LINES;

	#ifdef MCU_Act_As_Mater
	SPI1CFG.Device_Mode = SPI_DEVICE_MODE_MASTER;
	//SPI1CFG.IRQ_Enable = SPI_IRQ_Enable_NONE;
	SPI1CFG.IRQ_Enable.ENABLE = SPI_DISABLE_IRQ;

	SPI1CFG.NSS = SPI_NSS_Soft_NSSInternalSoft_Set;
	SPI1CFG.P_IRQ_callBack = NULL;

	GPIO_PinConfig_t PinCfg;
	PinCfg.GPIO_PinNumber = GPIO_PIN_4;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;

	#endif

	#ifdef MCU_Act_As_Slave
	SPI1CFG.Device_Mode = SPI_DEVICE_MODE_SLAVE;
	SPI1CFG.IRQ_Enable.ENABLE = SPI_ENABLE_IRQ;
	SPI1CFG.IRQ_Enable.RXNE = SPI_ENABLE_IRQ;
	SPI1CFG.IRQ_Enable.TXE = SPI_DISABLE_IRQ;
	SPI1CFG.IRQ_Enable.ERRiI = SPI_DISABLE_IRQ;
	SPI1CFG.NSS = SPI_NSS_Hard_Slave;
	SPI1CFG.P_IRQ_callBack = SPI1_IRQ_CallBack;

	#endif
	MCAL_SPI_Init(SPI1, &SPI1CFG);
	MCAL_SPI_GPIO_Set_Pins(SPI1);

	// configure PA4 as chip select
	GPIO_PinConfig_t PinCfg;
	PinCfg.GPIO_PinNumber = GPIO_PIN_4;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;

	MCAL_GPIO_Init(GPIOA, &PinCfg);
	// idle slave select as 1 high
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);

	while(1)
	{

	}
}



//		//PA1 >>>Connected external  PUR (default 1)
//		if( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) //Press
//		{
//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
//			while( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0); //Single Press
//		}
//
//		//PA13 >>>Connected external  PDR (default 0)
//		if( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1) //Multi Press
//		{
//			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
//		}
//		wait(4);








//void GPIO_init()
//{
//	GPIO_PinConfig_t PinCfg;
//
//
//	//PA1 IN HighZ Floating input (reset state)
//	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
//	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
//	MCAL_GPIO_Init(GPIOA, &PinCfg);
//
//	//PB1 output push/pull mode
//	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
//	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
//	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
//	MCAL_GPIO_Init(GPIOB, &PinCfg);
//	//==========================================
//
//	//PA13 IN HighZ
//	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
//	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
//	MCAL_GPIO_Init(GPIOA, &PinCfg);
//
//	//PB13 output push/pull mode
//	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
//	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
//	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
//	MCAL_GPIO_Init(GPIOB, &PinCfg);
//}
